# hexo-theme-teal
# https://github.com/Zoctan/hexo-theme-teal
menu:
  home:                   /
  archives:               /archives
  tags:                   /tags
  th-list:                /categories
  user:                   /about

# 你的头像url
avatar:                   /img/avatar.png
# avatar link
avatar_link:              /about
# 头像背景图
brand:                    /img/brand.png
# favicon
favicon:                  /img/favicon.ico

socail:
  github:                 https://github.com/
  stack-overflow:         https://stackoverflow.com/users/

# 设置 Android L Chrome 浏览器状态栏颜色
color:                    "#009688"

# 文章截断
excerpt_render:           false
excerpt_length:           48
excerpt_link:             阅读全文...
mathjax:                  true
archive_yearly:           true

# 是否显示文章最后更新时间
show_last_updated:        true

# 是否开启分享
share:                    true

# 是否开启打赏，关闭 reward:       false
reward:
  title:                  赏包辣条钱吧(๑•ᴗ•๑)~
  wechat:                 /img/wechat.png     #微信，关闭设为 false
  alipay:                 /img/alipay.png     #支付宝，关闭设为 false

# 是否开启搜索
search:                   true

# 是否大屏幕下文章页隐藏导航
hideMenu:                 true

# 是否开启toc
# toc:                    false
toc:
  list_number:            true  # 是否显示数字排序

# 文章页留言内容，hexo中所有变量及辅助函数等均可调用，具体请查阅 hexo.io
postMessage:              文章页留言内容

# 站长统计，如要开启，输入CNZZ站点id，如 cnzz: 1255152447
cnzz:

# 百度统计，如要开启，改为你的 key
baidu_tongji:

# 腾讯分析，如要开启，输入站点id
tajs:

# google
google_analytics:         false
google_site_verification: false

# less
less:
  compress:               true
  paths:
    - source/css/style.less

# 是否使用 gitment，https://github.com/imsun/gitment
gitment:                  false
# gitment:
#   owner:
#   repo:
#   client_id:
#   client_secret:

# 规范网址
# 让搜索引擎重定向你的不同域名、不同子域、同域不同目录的站点到你期望的路径
# https://support.google.com/webmasters/answer/139066
# 假设配置为 canonical:        http://imys.net，那么从搜索引擎中 www.imys.net 进入会重定向到 imys.net
canonical:                false

# 版权起始年份
since_year:               2017

# “不蒜子”访问量统计，详见 http://ibruce.info/2015/04/04/busuanzi/
visit_counter:            true

# 设置为 true 发布后将使用 unpkg cdn 最新的主题样式
# 如果想让你的自定义样式生效，把此项设为 false
cdn:                      true

# 设置为 true 将使用 lightbox render 图片
lightbox:                 true

# icp备案号  ICP_license:    京ICP备1234556号-1
ICP_license:              false
